// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Avito-courses/course-go-avito-domovonok/internal/handler (interfaces: courierService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/courier_service_mock.go -package=mocks github.com/Avito-courses/course-go-avito-domovonok/internal/handler courierService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Avito-courses/course-go-avito-domovonok/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockcourierService is a mock of courierService interface.
type MockcourierService struct {
	ctrl     *gomock.Controller
	recorder *MockcourierServiceMockRecorder
	isgomock struct{}
}

// MockcourierServiceMockRecorder is the mock recorder for MockcourierService.
type MockcourierServiceMockRecorder struct {
	mock *MockcourierService
}

// NewMockcourierService creates a new mock instance.
func NewMockcourierService(ctrl *gomock.Controller) *MockcourierService {
	mock := &MockcourierService{ctrl: ctrl}
	mock.recorder = &MockcourierServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierService) EXPECT() *MockcourierServiceMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockcourierService) CreateCourier(ctx context.Context, courier *model.Courier) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", ctx, courier)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockcourierServiceMockRecorder) CreateCourier(ctx, courier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockcourierService)(nil).CreateCourier), ctx, courier)
}

// GetCourier mocks base method.
func (m *MockcourierService) GetCourier(ctx context.Context, id int64) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourier", ctx, id)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourier indicates an expected call of GetCourier.
func (mr *MockcourierServiceMockRecorder) GetCourier(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourier", reflect.TypeOf((*MockcourierService)(nil).GetCourier), ctx, id)
}

// HealthCheck mocks base method.
func (m *MockcourierService) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockcourierServiceMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockcourierService)(nil).HealthCheck), ctx)
}

// ListCouriers mocks base method.
func (m *MockcourierService) ListCouriers(ctx context.Context) ([]*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCouriers", ctx)
	ret0, _ := ret[0].([]*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCouriers indicates an expected call of ListCouriers.
func (mr *MockcourierServiceMockRecorder) ListCouriers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCouriers", reflect.TypeOf((*MockcourierService)(nil).ListCouriers), ctx)
}

// UpdateCourier mocks base method.
func (m *MockcourierService) UpdateCourier(ctx context.Context, courier *model.Courier) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, courier)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockcourierServiceMockRecorder) UpdateCourier(ctx, courier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockcourierService)(nil).UpdateCourier), ctx, courier)
}
