// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Avito-courses/course-go-avito-domovonok/internal/factory (interfaces: DeliveryTimeCalculator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/delivery_time_calculator_mock.go -package=mocks github.com/Avito-courses/course-go-avito-domovonok/internal/factory DeliveryTimeCalculator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDeliveryTimeCalculator is a mock of DeliveryTimeCalculator interface.
type MockDeliveryTimeCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryTimeCalculatorMockRecorder
	isgomock struct{}
}

// MockDeliveryTimeCalculatorMockRecorder is the mock recorder for MockDeliveryTimeCalculator.
type MockDeliveryTimeCalculatorMockRecorder struct {
	mock *MockDeliveryTimeCalculator
}

// NewMockDeliveryTimeCalculator creates a new mock instance.
func NewMockDeliveryTimeCalculator(ctrl *gomock.Controller) *MockDeliveryTimeCalculator {
	mock := &MockDeliveryTimeCalculator{ctrl: ctrl}
	mock.recorder = &MockDeliveryTimeCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryTimeCalculator) EXPECT() *MockDeliveryTimeCalculatorMockRecorder {
	return m.recorder
}

// CalculateDeadline mocks base method.
func (m *MockDeliveryTimeCalculator) CalculateDeadline(fromTime time.Time) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateDeadline", fromTime)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CalculateDeadline indicates an expected call of CalculateDeadline.
func (mr *MockDeliveryTimeCalculatorMockRecorder) CalculateDeadline(fromTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateDeadline", reflect.TypeOf((*MockDeliveryTimeCalculator)(nil).CalculateDeadline), fromTime)
}
