// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Avito-courses/course-go-avito-domovonok/internal/factory (interfaces: DeliveryTimeCalculatorFactory)
//
// Generated by this command:
//
//	mockgen -destination=mocks/delivery_time_calculator_factory_mock.go -package=mocks github.com/Avito-courses/course-go-avito-domovonok/internal/factory DeliveryTimeCalculatorFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	factory "github.com/Avito-courses/course-go-avito-domovonok/internal/factory"
	gomock "go.uber.org/mock/gomock"
)

// MockDeliveryTimeCalculatorFactory is a mock of DeliveryTimeCalculatorFactory interface.
type MockDeliveryTimeCalculatorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryTimeCalculatorFactoryMockRecorder
	isgomock struct{}
}

// MockDeliveryTimeCalculatorFactoryMockRecorder is the mock recorder for MockDeliveryTimeCalculatorFactory.
type MockDeliveryTimeCalculatorFactoryMockRecorder struct {
	mock *MockDeliveryTimeCalculatorFactory
}

// NewMockDeliveryTimeCalculatorFactory creates a new mock instance.
func NewMockDeliveryTimeCalculatorFactory(ctrl *gomock.Controller) *MockDeliveryTimeCalculatorFactory {
	mock := &MockDeliveryTimeCalculatorFactory{ctrl: ctrl}
	mock.recorder = &MockDeliveryTimeCalculatorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryTimeCalculatorFactory) EXPECT() *MockDeliveryTimeCalculatorFactoryMockRecorder {
	return m.recorder
}

// CreateCalculator mocks base method.
func (m *MockDeliveryTimeCalculatorFactory) CreateCalculator(transportType string) factory.DeliveryTimeCalculator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCalculator", transportType)
	ret0, _ := ret[0].(factory.DeliveryTimeCalculator)
	return ret0
}

// CreateCalculator indicates an expected call of CreateCalculator.
func (mr *MockDeliveryTimeCalculatorFactoryMockRecorder) CreateCalculator(transportType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCalculator", reflect.TypeOf((*MockDeliveryTimeCalculatorFactory)(nil).CreateCalculator), transportType)
}
