// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Avito-courses/course-go-avito-domovonok/internal/service (interfaces: deliveryRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/delivery_repository_mock.go -package=mocks github.com/Avito-courses/course-go-avito-domovonok/internal/service deliveryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Avito-courses/course-go-avito-domovonok/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockdeliveryRepository is a mock of deliveryRepository interface.
type MockdeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryRepositoryMockRecorder
	isgomock struct{}
}

// MockdeliveryRepositoryMockRecorder is the mock recorder for MockdeliveryRepository.
type MockdeliveryRepositoryMockRecorder struct {
	mock *MockdeliveryRepository
}

// NewMockdeliveryRepository creates a new mock instance.
func NewMockdeliveryRepository(ctrl *gomock.Controller) *MockdeliveryRepository {
	mock := &MockdeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockdeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryRepository) EXPECT() *MockdeliveryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockdeliveryRepository) Create(ctx context.Context, delivery *model.Delivery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, delivery)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockdeliveryRepositoryMockRecorder) Create(ctx, delivery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockdeliveryRepository)(nil).Create), ctx, delivery)
}

// DeleteByOrderID mocks base method.
func (m *MockdeliveryRepository) DeleteByOrderID(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByOrderID", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByOrderID indicates an expected call of DeleteByOrderID.
func (mr *MockdeliveryRepositoryMockRecorder) DeleteByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByOrderID", reflect.TypeOf((*MockdeliveryRepository)(nil).DeleteByOrderID), ctx, orderID)
}

// GetAvailableCourier mocks base method.
func (m *MockdeliveryRepository) GetAvailableCourier(ctx context.Context) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableCourier", ctx)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableCourier indicates an expected call of GetAvailableCourier.
func (mr *MockdeliveryRepositoryMockRecorder) GetAvailableCourier(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableCourier", reflect.TypeOf((*MockdeliveryRepository)(nil).GetAvailableCourier), ctx)
}

// GetByOrderID mocks base method.
func (m *MockdeliveryRepository) GetByOrderID(ctx context.Context, orderID string) (*model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderID indicates an expected call of GetByOrderID.
func (mr *MockdeliveryRepositoryMockRecorder) GetByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderID", reflect.TypeOf((*MockdeliveryRepository)(nil).GetByOrderID), ctx, orderID)
}

// ReleaseExpiredDeliveries mocks base method.
func (m *MockdeliveryRepository) ReleaseExpiredDeliveries(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseExpiredDeliveries", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseExpiredDeliveries indicates an expected call of ReleaseExpiredDeliveries.
func (mr *MockdeliveryRepositoryMockRecorder) ReleaseExpiredDeliveries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseExpiredDeliveries", reflect.TypeOf((*MockdeliveryRepository)(nil).ReleaseExpiredDeliveries), ctx)
}
